- name: Install Prometheus and Grafana
  hosts: monitoring
  become: true
  tasks:

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
          - curl
        update_cache: yes

    - name: Create Prometheus user and directories
      user:
        name: prometheus
        shell: /sbin/nologin
      register: prometheus_user

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus to specific folder
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes
        creates: /opt/prometheus-2.45.0.linux-amd64

    - name: Install Prometheus binaries
      copy:
        src: "/opt/prometheus-2.45.0.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        remote_src : yes
      loop:
        - prometheus
        - promtool


    - name: Copy Prometheus config
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: ['localhost:9090']
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create Prometheus systemd unit
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.console.templates=/usr/local/bin/consoles \
            --web.console.libraries=/usr/local/bin/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

    - name: Install Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        update_cache: yes
        state: present

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started


